# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 14:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('werewolf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchup',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
    ]
