# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 21:29
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0003_auto_20160419_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='present',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=[], null=True, size=None),
        ),
    ]
