# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0004_auto_20160419_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='num_present',
            field=models.IntegerField(default=0),
        ),
    ]
