# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0005_game_num_present'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='num_present',
        ),
    ]
