# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0006_remove_game_num_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.FilePathField(null=True, path=b'/static/werewolf/images/'),
        ),
    ]
