# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0007_character_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.FilePathField(blank=True, null=True, path=b'/static/werewolf/images', recursive=True),
        ),
    ]
