# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0008_auto_20160420_0207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='started_date',
            new_name='created_date'
        ),
        migrations.AddField(
            model_name='game',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
