# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0010_auto_20160423_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switch',
            name='victim',
        ),
        migrations.AddField(
            model_name='switch',
            name='after',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='after', to='werewolf.Matchup'),
        ),
        migrations.AddField(
            model_name='switch',
            name='before',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='before', to='werewolf.Matchup'),
        ),
        migrations.AddField(
            model_name='switch',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='werewolf.Game'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='switch',
            name='initiator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='initiator', to='werewolf.Matchup'),
        ),
    ]
