# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0011_auto_20160424_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='stage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='current_stage',
            field=models.IntegerField(default=0),
        ),
    ]
