# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0012_auto_20160424_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='num_cards_selected',
            field=models.IntegerField(default=0),
        ),
    ]
