# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 22:21
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0013_game_num_cards_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ready_to_advance',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=[], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='game',
            name='present',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=[], null=True, size=None),
        ),
    ]
