# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0014_auto_20160424_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='werewolf.Game')),
                ('voted_for', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='voted_for', to='werewolf.Matchup')),
                ('voter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='voter', to='werewolf.Matchup')),
            ],
        ),
    ]
