# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 00:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0016_remove_matchup_is_final'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='started',
            new_name='finished',
        ),
    ]
