# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0017_auto_20160426_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='team',
            field=models.CharField(choices=[(b'villager', b'Villager Team'), (b'werewolf', b'Werewolf Team'), (b'tanner', b'Tanner Team')], default='villager', max_length=30),
            preserve_default=False,
        ),
    ]
