# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 02:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0020_auto_20160426_0242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='winning_team',
            new_name='winning_teams',
        ),
    ]
