# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0021_auto_20160426_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voted_for',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voted_for', to='werewolf.Matchup'),
        ),
    ]
